package com.haulmont.testtask.view;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.navigator.View;
import com.vaadin.ui.declarative.Design;

import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Grid;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class DoctorView extends VerticalLayout implements View {
    private Button addItemButton;
    private Grid<com.haulmont.testtask.model.Doctor> grid;
    private Button showSatisticsButton;
    private Grid<com.haulmont.testtask.model.Doctor> statisticGrid;

    public DoctorView( ) {
        Design.read(this);
    }

    public Button getAddItemButton() {
        return addItemButton;
    }

    public Grid<com.haulmont.testtask.model.Doctor> getGrid() {
        return grid;
    }

    public Button getShowSatisticsButton() {
        return showSatisticsButton;
    }

    public Grid<com.haulmont.testtask.model.Doctor> getStatisticGrid() {
        return statisticGrid;
    }

}
