package com.haulmont.testtask.view;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Button;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class EditPatientView extends AbsoluteLayout {
    private AbsoluteLayout editLayout;
    private TextField nameField;
    private TextField surnameField;
    private TextField patronymicField;
    private TextField phoneField;
    private Button editButton;
    private Button cancelButton;

    public EditPatientView() {
        Design.read(this);
    }

    public AbsoluteLayout getEditLayout() {
        return editLayout;
    }

    public TextField getNameField() {
        return nameField;
    }

    public TextField getSurnameField() {
        return surnameField;
    }

    public TextField getPatronymicField() {
        return patronymicField;
    }

    public TextField getPhoneField() {
        return phoneField;
    }

    public Button getEditButton() {
        return editButton;
    }

    public Button getCancelButton() {
        return cancelButton;
    }

}
