package com.haulmont.testtask.view;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class EditRecipeView extends AbsoluteLayout {
    private TextArea descriptionTextArea;
    private ComboBox priorityCombobox;
    private Button okButton;
    private AbsoluteLayout doctorLayout;
    private Label doctorsFieldLabel;
    private TextField doctorNameField;
    private TextField doctorSurnameField;
    private TextField doctorPatronymicField;
    private AbsoluteLayout patientLayout;
    private TextField patientNameField;
    private TextField patientSurnameField;
    private TextField patientPatronymicField;
    private TextField deadlinesField;
    private Button cancelButton;

    public EditRecipeView() {
        Design.read(this);
    }

    public TextArea getDescriptionTextArea() {
        return descriptionTextArea;
    }

    public ComboBox getPriorityCombobox() {
        return priorityCombobox;
    }

    public Button getOkButton() {
        return okButton;
    }

    public AbsoluteLayout getDoctorLayout() {
        return doctorLayout;
    }

    public Label getDoctorsFieldLabel() {
        return doctorsFieldLabel;
    }

    public TextField getDoctorNameField() {
        return doctorNameField;
    }

    public TextField getDoctorSurnameField() {
        return doctorSurnameField;
    }

    public TextField getDoctorPatronymicField() {
        return doctorPatronymicField;
    }

    public AbsoluteLayout getPatientLayout() {
        return patientLayout;
    }

    public TextField getPatientNameField() {
        return patientNameField;
    }

    public TextField getPatientSurnameField() {
        return patientSurnameField;
    }

    public TextField getPatientPatronymicField() {
        return patientPatronymicField;
    }

    public TextField getDeadlinesField() {
        return deadlinesField;
    }

    public Button getCancelButton() {
        return cancelButton;
    }

}
